<?php
return array (
  'DB_TYPE' => 'mysql',
  'DB_HOST' => 'localhost',
  'DB_NAME' => 'zhizhao',
  'DB_USER' => 'root',
  'DB_PWD' => 'zwt12345',
  'DB_PORT' => '3306',
  'DB_PREFIX' => 'zz_',
  'TMPL_PARSE_STRING' => 
  array (
    '__STATIC__' => '/Public/Static',
    '__IMG__' => '/Public/Admin/images',
    '__CSS__' => '/Public/Admin/css',
    '__JS__' => '/Public/Admin/js',
  ),
  'TMPL_L_DELIM' => '{@',
  'TMPL_R_DELIM' => '@}',
  'LOAD_EXT_FILE' => 'functions',
  'UPLOAD_MAX_SIZE' => 1000000,
  'UPLOAD_PATH' => './Uploads/',
  'UPLOAD_EXTS' => 
  array (
    0 => 'jpg',
    1 => 'jpeg',
    2 => 'gif',
    3 => 'png',
  ),
  'POINT_LOGIN' => '5',
  'POINT_ARTICLE' => '5',
  'POINT_COMMENT' => '1',
  'POINT_LETTER' => '2',
  'POINT_COLLECT' => '1',
  'POINT_ZAN' => '1',
  'LEVEL_LOGIN' => '5',
  'LEVEL_ARTICLE' => '8',
  'LEVEL_COMMENT' => '2',
  'LEVEL_LETTER' => '2',
  'LEVEL_COLLECT' => '1',
  'LEVEL_ZAN' => '1',
  'LV1' => '2',
  'LV2' => '6',
  'LV3' => '16',
  'LV4' => '40',
  'LV5' => '80',
  'LV6' => '140',
  'LV7' => '250',
  'LV8' => '400',
  'LV9' => '620',
  'LV10' => '750',
  'LV11' => '1000',
  'LV12' => '1500',
  'LV13' => '2500',
  'LV14' => '4000',
  'LV15' => '6000',
  'LV16' => '7500',
  'LV17' => '9000',
  'LV18' => '10000',
  'LV19' => '12000',
  'LV20' => '18000',
);
?>